modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Centrifuge-Tiers-Reproduced/issues/new/choose"
[[mods]]
modId="centrifugetiersreproduced"
version="${file.jarVersion}"
displayName="Centrifuge Tiers Reproduced"
displayURL="https://www.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced"
logoFile="example.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="This mod adds tiers to the centrifuges from Productive Bees."

[[dependencies.centrifugetiersreproduced]]
    modId="productivebees"
    mandatory=true
    versionRange="[0.9.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.centrifugetiersreproduced]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.79,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.centrifugetiersreproduced]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"